/*
 Sam Buriima
generated by Saburi Tools
 */
package com.saburi.finance.dbaccess;

import com.saburi.common.dbaccess.DBAccess;
import com.saburi.common.dbaccess.LookupDataDA;
import com.saburi.finance.entities.ItemPriceGroup;
import javafx.beans.property.*;
import java.util.ArrayList;
import com.saburi.common.entities.AppRevisionEntity;
import java.util.List;
import javafx.util.Pair;
import com.saburi.common.utils.SearchColumn;
import com.saburi.common.utils.SearchColumn.SearchDataTypes;
import org.hibernate.envers.RevisionType;
import com.saburi.finance.entities.Item;
import com.saburi.common.entities.LookupData;
import static com.saburi.common.utils.Utilities.formatNumber;

public class ItemPriceGroupDA extends DBAccess {
    
    private ItemPriceGroup itemPriceGroup = new ItemPriceGroup();
    private final SimpleStringProperty itemDisplay = new SimpleStringProperty(this, "itemDisplay");
    private final SimpleObjectProperty itemID = new SimpleObjectProperty(this, "itemID");
    private Item item;
    private final SimpleStringProperty priceGroupDisplay = new SimpleStringProperty(this, "priceGroupDisplay");
    private final SimpleObjectProperty priceGroupID = new SimpleObjectProperty(this, "priceGroupID");
    private LookupData priceGroup;
    private final SimpleStringProperty itemPriceGroupID = new SimpleStringProperty(this, "itemPriceGroupID");
    private final SimpleDoubleProperty unitPrice = new SimpleDoubleProperty(this, "unitPrice");
    private final SimpleStringProperty unitPriceDisplay = new SimpleStringProperty(this, "unitPriceDisplay");
    private final SimpleDoubleProperty discount = new SimpleDoubleProperty(this, "discount");
    private final SimpleStringProperty discountDisplay = new SimpleStringProperty(this, "discountDisplay");
    
    public ItemPriceGroupDA() {
        createSearchColumns();
    }
    
    public ItemPriceGroupDA(String persistenceUnit) {
        super(persistenceUnit);
    }
    
    public ItemPriceGroupDA(ItemPriceGroup itemPriceGroup) {
        this.itemPriceGroup = itemPriceGroup;
        initialseProprties();
        createSearchColumns();
    }
    
    public ItemPriceGroupDA(String persistenceUnit, ItemPriceGroup itemPriceGroup) {
        super(persistenceUnit);
        this.itemPriceGroup = itemPriceGroup;
        initialseProprties();
        createSearchColumns();
    }
    
    public ItemPriceGroupDA(ItemDA itemDA, LookupDataDA priceGroupDA,  double unitPrice, double discount) {
        this.itemPriceGroup = new ItemPriceGroup(itemDA != null ? (Item) itemDA.getDBEntity() : null, priceGroupDA != null ? (LookupData) priceGroupDA.getDBEntity() : null, unitPrice, discount);
        initialseProprties();
        createSearchColumns();
    }
    
    public ItemPriceGroupDA(String persistenceUnit, ItemDA itemDA, LookupDataDA priceGroupDA, double unitPrice, double discount) {
        super(persistenceUnit);
        this.itemPriceGroup = new ItemPriceGroup(itemDA != null ? (Item) itemDA.getDBEntity() : null, priceGroupDA != null ? (LookupData) priceGroupDA.getDBEntity() : null,  unitPrice, discount);
        initialseProprties();
        createSearchColumns();
    }
    
    public Item getItem() {
        return item;
    }
    
    public Object getItemID() {
        return itemID.get();
    }
    
    public String getItemDisplay() {
        return itemDisplay.get();
    }
    
    public ItemDA getItemDA() {
        if (this.item == null) {
            return new ItemDA();
        } else {
            return new ItemDA(this.item);
        }
    }
    
    public Pair<String, Object> getItemPair() {
        if (this.getItemDA() == null) {
            return new Pair<>("", "");
        } else {
            return this.getItemDA().keyValuePair();
        }
    }
    
    public void setItem(Item item) {
        itemPriceGroup.setItem(item);
        this.item = item;
    }
    
    public LookupData getPriceGroup() {
        return priceGroup;
    }
    
    public Object getPriceGroupID() {
        return priceGroupID.get();
    }
    
    public String getPriceGroupDisplay() {
        return priceGroupDisplay.get();
    }
    
    public LookupDataDA getPriceGroupDA() {
        if (this.priceGroup == null) {
            return new LookupDataDA();
        } else {
            return new LookupDataDA(this.priceGroup);
        }
    }
    
    public Pair<String, Object> getPriceGroupPair() {
        if (this.getPriceGroupDA() == null) {
            return new Pair<>("", "");
        } else {
            return this.getPriceGroupDA().keyValuePair();
        }
    }
    
    public void setPriceGroup(LookupData priceGroup) {
        itemPriceGroup.setPriceGroup(priceGroup);
        this.priceGroup = priceGroup;
        this.priceGroupID.set(priceGroup.getId());
        this.priceGroupDisplay.set(priceGroup.getDisplayKey());
    }
    
    public String getItemPriceGroupID() {
        return itemPriceGroupID.get();
    }
    
   
    
    public double getUnitPrice() {
        return unitPrice.get();
    }
    
    public String getUnitPriceDisplay() {
        return unitPriceDisplay.get();
    }
    
    public void setUnitPrice(double unitPrice) {
        itemPriceGroup.setUnitPrice(unitPrice);
        this.unitPrice.set(unitPrice);
        this.unitPriceDisplay.set(formatNumber(unitPrice));
    }
    
    public double getDiscount() {
        return discount.get();
    }
    
    public String getDiscountDisplay() {
        return discountDisplay.get();
    }
    
    public void setDiscount(double discount) {
        itemPriceGroup.setDiscount(discount);
        this.discount.set(discount);
        this.discountDisplay.set(formatNumber(discount));
    }
    
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof ItemPriceGroupDA)) {
            return false;
        }
        
        ItemPriceGroupDA itemPriceGroupDA = (ItemPriceGroupDA) o;
        
        if (itemPriceGroupDA.getDBEntity() == null || this.getDBEntity() == null) {
            return false;
        }
        return this.getId().equals(itemPriceGroupDA.getId());
    }
    
    @Override
    public int hashCode() {
        return itemPriceGroup.getId().hashCode();
    }
    
    private void initialseProprties() {
        this.dBEntity = itemPriceGroup;
        this.item = itemPriceGroup.getItem();
        if (this.item != null) {
            this.itemID.set(item.getId());
            this.itemDisplay.set(item.getDisplayKey());
        }
        this.priceGroup = itemPriceGroup.getPriceGroup();
        if (this.priceGroup != null) {
            this.priceGroupID.set(priceGroup.getId());
            this.priceGroupDisplay.set(priceGroup.getDisplayKey());
        }
        this.itemPriceGroupID.set(itemPriceGroup.getItemPriceGroupID());
        this.unitPrice.set(itemPriceGroup.getUnitPrice());
        this.unitPriceDisplay.set(formatNumber(itemPriceGroup.getUnitPrice()));
        this.discount.set(itemPriceGroup.getDiscount());
        this.discountDisplay.set(formatNumber(itemPriceGroup.getDiscount()));
        initCommonProprties();
    }
    
    private void createSearchColumns() {
        this.searchColumns.add(new SearchColumn("itemID", "Item ID", this.itemID.get(), SearchDataTypes.STRING, SearchColumn.SearchType.Equal, false));
        this.searchColumns.add(new SearchColumn("itemDisplay", "Item", this.itemDisplay.get(), SearchDataTypes.STRING));
        this.searchColumns.add(new SearchColumn("priceGroupID", "Price Group ID", this.priceGroupID.get(), SearchDataTypes.STRING, SearchColumn.SearchType.Equal, false));
        this.searchColumns.add(new SearchColumn("priceGroupDisplay", "Price Group", this.priceGroupDisplay.get(), SearchDataTypes.STRING));
        this.searchColumns.add(new SearchColumn("itemPriceGroupID", "Item Price Group ID", this.itemPriceGroupID.get(), SearchDataTypes.STRING));
        this.searchColumns.add(new SearchColumn("unitPrice", "UnitPrice", this.unitPrice.get(), SearchDataTypes.NUMBER));
        this.searchColumns.add(new SearchColumn("discount", "Discount", this.discount.get(), SearchDataTypes.NUMBER));
        this.searchColumns.addAll(this.getDefaultSearchColumns());
    }
    
    @Override
    public List<SearchColumn> getSearchColumns() {
        return this.searchColumns;
    }
    
    @Override
    public Object getId() {
        return this.itemPriceGroup.getId();
    }
    
    @Override
    public String getDisplayKey() {
        return this.itemPriceGroup.getDisplayKey();
    }
    
    public static List<ItemPriceGroupDA> getItemPriceGroupDAs(List<ItemPriceGroup> itemPriceGroups) {
        List<ItemPriceGroupDA> list = new ArrayList<>();
        itemPriceGroups.forEach((itemPriceGroup) -> {
            list.add(new ItemPriceGroupDA(itemPriceGroup));
        });
        return list;
    }
    
    public static List<ItemPriceGroup> getItemPriceGroupList(List<ItemPriceGroupDA> itemPriceGroupDAs) {
        List<ItemPriceGroup> itemPriceGroups = new ArrayList<>();
        itemPriceGroupDAs.forEach(a -> itemPriceGroups.add(a.itemPriceGroup));
        return itemPriceGroups;
    }
    
    public boolean save() throws Exception {
        return super.persist(this.itemPriceGroup);
        
    }
    
    public boolean update() throws Exception {
        return super.merge(this.itemPriceGroup);
        
    }
    
    public boolean delete() {
        return super.remove(this.itemPriceGroup);
        
    }
    
    public ItemPriceGroup getItemPriceGroup(String itemPriceGroupID) {
        return (ItemPriceGroup) super.find(ItemPriceGroup.class, itemPriceGroupID);
    }
    
    public List<ItemPriceGroup> getItemPriceGroups() {
        return super.find(ItemPriceGroup.class);
    }
    
    @Override
    public List<DBAccess> get() {
        List<DBAccess> list = new ArrayList<>();
        selectQuery(ItemPriceGroup.class).forEach(o -> list.add(new ItemPriceGroupDA((ItemPriceGroup) o)));
        if (entityManager != null) {
            entityManager.close();
        }
        return list;
    }
    
    public ItemPriceGroupDA get(String itemPriceGroupID) throws Exception {
        ItemPriceGroup oItemPriceGroup = getItemPriceGroup(itemPriceGroupID);
        if (oItemPriceGroup == null) {
            throw new Exception("No Record with id: " + itemPriceGroupID);
        }
        return new ItemPriceGroupDA(oItemPriceGroup);
    }
    
    public List<ItemPriceGroupDA> get(String columName, Object value) {
        List<ItemPriceGroupDA> list = new ArrayList<>();
        super.selectQuery(ItemPriceGroup.class, columName, value).forEach(da -> list.add(new ItemPriceGroupDA((ItemPriceGroup) da)));
        if (entityManager != null) {
            entityManager.close();
        }
        return list;
    }
    
    public List<ItemPriceGroupDA> toDaList(List<ItemPriceGroup> itemPriceGroups) {
        List<ItemPriceGroupDA> itemPriceGroupDAs = new ArrayList<>();
        itemPriceGroups.forEach(s -> itemPriceGroupDAs.add(new ItemPriceGroupDA(s)));
        return itemPriceGroupDAs;
    }
    
    public List<DBAccess> toDBAccessList(List<ItemPriceGroup> itemPriceGroups) {
        List<DBAccess> dbAccesses = new ArrayList<>();
        itemPriceGroups.forEach(s -> dbAccesses.add(new ItemPriceGroupDA(s)));
        return dbAccesses;
    }
    
    public int getMax(String columnName) {
        return super.getMax(ItemPriceGroup.class, columnName);
    }
    
    public int getMax(String columnName, String comparatorColumn, Object comparatorVaue) {
        return super.getMax(ItemPriceGroup.class, columnName, comparatorColumn, comparatorVaue);
    }
    
    public List<ItemPriceGroup> getItemPriceGroups(String columName, Object value) {
        return super.find(ItemPriceGroup.class, columName, value);
    }
    
    @Override
    public List<DBAccess> getRevisions() {
        try {
            
            List<Object[]> list = getEntityRevisions(ItemPriceGroup.class);
            List<DBAccess> dBAccesses = new ArrayList<>();
            list.forEach(e -> {
                
                ItemPriceGroupDA itemPriceGroupDA = new ItemPriceGroupDA((ItemPriceGroup) e[0]);
                itemPriceGroupDA.revisionEntity = (AppRevisionEntity) e[1];
                itemPriceGroupDA.oRevisionType = (RevisionType) e[2];
                itemPriceGroupDA.initRevProprties();
                itemPriceGroupDA.searchColumns.addAll(itemPriceGroupDA.getRevSearchColumns());
                dBAccesses.add(itemPriceGroupDA);
                
            });
            
            return dBAccesses;
        } catch (Exception e) {
            throw e;
        } finally {
            if (entityManager == null) {
                entityManager.close();
            }
        }
        
    }
    
}
