/*
 Sam Buriima
generated by Saburi Tools
 */
package com.saburi.finance.entities;

import com.saburi.common.entities.DBEntity;
import com.saburi.common.entities.LookupData;
import javax.persistence.Entity;
import javax.persistence.Id;
import org.hibernate.envers.Audited;
import org.hibernate.envers.RelationTargetAuditMode;
import javax.validation.constraints.NotNull;
import javax.persistence.JoinColumn;
import javax.persistence.ForeignKey;
import javax.persistence.OneToOne;
import javax.persistence.Column;
import javax.validation.constraints.Size;

@Entity
@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
public class ItemPriceGroup extends DBEntity {

    @NotNull(message = "The field: Item cannot be null")
    @OneToOne
    @JoinColumn(name = "itemID", foreignKey = @ForeignKey(name = "fkItemIDItemPriceGroup"))
    private Item item;
    @NotNull(message = "The field: Price Group cannot be null")
    @OneToOne
    @JoinColumn(name = "priceGroupID", foreignKey = @ForeignKey(name = "fkPriceGroupIDItemPriceGroup"))
    private LookupData priceGroup;
    @Id
    @NotNull(message = "The field: Item Price Group ID cannot be null")
    @Size(max = 20, message = "The field: Item Price Group ID size cannot be greater than 20")
    @Column(length = 20, updatable = false)
    private String itemPriceGroupID;
    private double unitPrice;
    private double discount;

    public ItemPriceGroup() {
    }

    public ItemPriceGroup(Item item, LookupData priceGroup, double unitPrice, double discount) {
        this.item = item;
        this.priceGroup = priceGroup;
        setItemPriceGroupID();
        this.unitPrice = unitPrice;
        this.discount = discount;

    }

    public Item getItem() {
        return item;
    }

    public void setItem(Item item) {
        this.item = item;
        setItemPriceGroupID();
    }

    public LookupData getPriceGroup() {
        return priceGroup;
    }

    public void setPriceGroup(LookupData priceGroup) {
        this.priceGroup = priceGroup;
        setItemPriceGroupID();
    }

    public String getItemPriceGroupID() {
       return itemPriceGroupID;
    }

    private void setItemPriceGroupID() {
         String itemPart = item==null?"":item.getItemID();
        String priceGroupPart = priceGroup==null?"":priceGroup.getLookupDataID();
        
        this.itemPriceGroupID = itemPart.concat(priceGroupPart);
    }

    public double getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(double unitPrice) {
        this.unitPrice = unitPrice;
    }

    public double getDiscount() {
        return discount;
    }

    public void setDiscount(double discount) {
        this.discount = discount;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof ItemPriceGroup)) {
            return false;
        }

        ItemPriceGroup itemPriceGroup = (ItemPriceGroup) o;

        return this.getId().equals(itemPriceGroup.getId());
    }

    @Override
    public int hashCode() {
        return this.itemPriceGroupID.hashCode();

    }

    @Override
    public Object getId() {
        return this.itemPriceGroupID;
    }

    @Override
    public String getDisplayKey() {
        return this.priceGroup.getDisplayKey();
    }

}
