/*
 Sam Buriima
generated by Saburi Tools
 */
package com.saburi.finance.entities;

import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import org.hibernate.envers.Audited;
import org.hibernate.envers.RelationTargetAuditMode;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import com.saburi.common.entities.DBEntity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.validation.constraints.NotNull;
import javax.persistence.JoinColumn;
import javax.persistence.ForeignKey;
import javax.persistence.OneToOne;

@Entity
@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
@Table(
        uniqueConstraints = @UniqueConstraint(columnNames = {"refundID", "receiptInvoiceID"}, name = "uqRefundReceiptInvoice")
)
public class RefundReceiptInvoice extends DBEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(updatable = false, nullable = false)
    private int refundReceiptInvoiceID;
    @NotNull(message = "The field: Refund cannot be null")
    @OneToOne
    @JoinColumn(name = "refundID", foreignKey = @ForeignKey(name = "fkRefundIDRefundReceiptInvoice"))
    private Refund refund;
    @NotNull(message = "The field: Receipt Invoice cannot be null")
    @OneToOne
    @JoinColumn(name = "receiptInvoiceID", foreignKey = @ForeignKey(name = "fkReceiptInvoiceIDRefundReceiptInvoice"))
    private ReceiptInvoice receiptInvoice;
    @NotNull(message = "The field: Amount cannot be null")
    @Column(name = "amount", nullable = false)
    private double amount;

    public RefundReceiptInvoice() {
    }

    public RefundReceiptInvoice(Refund refund, ReceiptInvoice receiptInvoice, double amount) {
        this.refund = refund;
        this.receiptInvoice = receiptInvoice;
        this.amount = amount;

    }

    public int getRefundReceiptInvoiceID() {
        return refundReceiptInvoiceID;
    }

    public void setRefundReceiptInvoiceID(int refundReceiptInvoiceID) {
        this.refundReceiptInvoiceID = refundReceiptInvoiceID;
    }

    public Refund getRefund() {
        return refund;
    }

    public void setRefund(Refund refund) {
        this.refund = refund;
    }

    public ReceiptInvoice getReceiptInvoice() {
        return receiptInvoice;
    }

    public void setReceiptInvoice(ReceiptInvoice receiptInvoice) {
        this.receiptInvoice = receiptInvoice;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null) {
            return false;
        }
        if (getClass() != o.getClass()) {
            return false;
        }
        final RefundReceiptInvoice refundReceiptInvoice = (RefundReceiptInvoice) o;
        if (!Objects.equals(this.refund, refundReceiptInvoice.refund)) {
            return false;
        }
        return Objects.equals(this.receiptInvoice, refundReceiptInvoice.receiptInvoice);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(this.refund) + Objects.hashCode(this.receiptInvoice);
    }

    @Override
    public Object getId() {
        return this.refundReceiptInvoiceID;
    }

    @Override
    public String getDisplayKey() {
        return this.refund.getDisplayKey() + " " + this.receiptInvoice.getDisplayKey();
    }

}
