/*
 Sam Buriima
generated by Saburi Tools
 */
package com.saburi.finance.entities;

import com.saburi.common.entities.DBEntity;
import com.saburi.common.entities.LookupData;
import javax.persistence.Entity;
import javax.persistence.Id;
import org.hibernate.envers.Audited;
import org.hibernate.envers.RelationTargetAuditMode;
import javax.validation.constraints.NotNull;
import javax.persistence.Column;
import javax.validation.constraints.Size;
import javax.persistence.JoinColumn;
import javax.persistence.ForeignKey;
import javax.persistence.OneToOne;

@Entity
@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
public class VendorPostingGroup extends DBEntity {

    @Column(updatable = false)
    private int idHelper;
    @Id
    @NotNull(message = "The field: Vendor Posting GroupID cannot be null")
    @Size(max = 20, message = "The field: Vendor Posting GroupID size cannot be greater than 20")
    @Column(length = 20, updatable = false)
    private String vendorPostingGroupID;
    @NotNull(message = "The field: Vendor Group cannot be null")
    @OneToOne
    @JoinColumn(name = "vendorGroupID", unique = true, foreignKey = @ForeignKey(name = "fkVendorGroupIDVendorPostingGroup"))
    private LookupData vendorGroup;
    @OneToOne
    @JoinColumn(name = "payableAccountID", foreignKey = @ForeignKey(name = "fkPayableAccountIDVendorPostingGroup"))
    private ChartAccount payableAccount;
    @OneToOne
    @JoinColumn(name = "serviceChargeAccountID", foreignKey = @ForeignKey(name = "fkServiceChargeAccountIDVendorPostingGroup"))
    private ChartAccount serviceChargeAccount;
    @OneToOne
    @JoinColumn(name = "paymentDiscountAccountID", foreignKey = @ForeignKey(name = "fkPaymentDiscountAccountIDVendorPostingGroup"))
    private ChartAccount paymentDiscountAccount;

    public VendorPostingGroup() {
    }

    public VendorPostingGroup(int idHelper, String vendorPostingGroupID, LookupData vendorGroup, ChartAccount payableAccount, ChartAccount serviceChargeAccount, ChartAccount paymentDiscountAccount) {
        this.idHelper = idHelper;
        this.vendorPostingGroupID = vendorPostingGroupID;
        this.vendorGroup = vendorGroup;
        this.payableAccount = payableAccount;
        this.serviceChargeAccount = serviceChargeAccount;
        this.paymentDiscountAccount = paymentDiscountAccount;

    }

    public int getIdHelper() {
        return idHelper;
    }

    public void setIdHelper(int idHelper) {
        this.idHelper = idHelper;
    }

    public String getVendorPostingGroupID() {
        return vendorPostingGroupID;
    }

    public void setVendorPostingGroupID(String vendorPostingGroupID) {
        this.vendorPostingGroupID = vendorPostingGroupID;
    }

    public LookupData getVendorGroup() {
        return vendorGroup;
    }

    public void setVendorGroup(LookupData vendorGroup) {
        this.vendorGroup = vendorGroup;
    }

    public ChartAccount getPayableAccount() {
        return payableAccount;
    }

    public void setPayableAccount(ChartAccount payableAccount) {
        this.payableAccount = payableAccount;
    }

    public ChartAccount getServiceChargeAccount() {
        return serviceChargeAccount;
    }

    public void setServiceChargeAccount(ChartAccount serviceChargeAccount) {
        this.serviceChargeAccount = serviceChargeAccount;
    }

    public ChartAccount getPaymentDiscountAccount() {
        return paymentDiscountAccount;
    }

    public void setPaymentDiscountAccount(ChartAccount paymentDiscountAccount) {
        this.paymentDiscountAccount = paymentDiscountAccount;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof VendorPostingGroup)) {
            return false;
        }

        VendorPostingGroup vendorPostingGroup = (VendorPostingGroup) o;

        return this.getId().equals(vendorPostingGroup.getId());
    }

    @Override
    public int hashCode() {
        return this.vendorPostingGroupID.hashCode();

    }

    @Override
    public Object getId() {
        return this.vendorPostingGroupID;
    }

    @Override
    public String getDisplayKey() {
        return this.vendorGroup.getDisplayKey();
    }

}
