/*
 Sam Buriima
generated by Saburi Tools
 */
package com.saburi.finance.controllers;

import com.saburi.common.controllers.EditController;
import com.saburi.common.utils.CommonEnums.EntryModes;
import com.saburi.common.utils.EditCell;
import static com.saburi.common.utils.FXUIUtils.addRow;
import static com.saburi.common.utils.FXUIUtils.errorMessage;
import static com.saburi.common.utils.FXUIUtils.getDate;
import static com.saburi.common.utils.FXUIUtils.getDouble;
import static com.saburi.common.utils.FXUIUtils.getEntity;
import static com.saburi.common.utils.FXUIUtils.getSelectedItem;
import static com.saburi.common.utils.FXUIUtils.getText;
import static com.saburi.common.utils.FXUIUtils.loadDBEntities;
import static com.saburi.common.utils.FXUIUtils.message;
import static com.saburi.common.utils.FXUIUtils.selectItem;
import static com.saburi.common.utils.FXUIUtils.setTableEditable;
import static com.saburi.common.utils.FXUIUtils.warningOk;
import com.saburi.common.utils.NumberToWord;
import com.saburi.common.utils.Utilities.FormMode;
import static com.saburi.common.utils.Utilities.defortNumberOptional;
import static com.saburi.common.utils.Utilities.formatNumber;
import java.net.URL;
import java.util.ResourceBundle;
import javafx.fxml.FXML;
import com.saburi.finance.dbaccess.SaleOrderDA;
import javafx.scene.control.TextField;
import javafx.scene.control.DatePicker;
import java.time.LocalDate;
;
import com.saburi.finance.utils.FinanceNavigate;
import javafx.scene.control.TextArea;
import javafx.scene.control.ComboBox;
import javafx.scene.control.MenuItem;
import com.saburi.finance.dbaccess.CustomerDA;
import com.saburi.finance.entities.Customer;
import com.saburi.finance.dbaccess.CurrencyDA;
import com.saburi.finance.dbaccess.ItemDA;
import com.saburi.finance.dbaccess.MeasureGroupDA;
import com.saburi.finance.dbaccess.MeasureRelationDA;
import com.saburi.finance.entities.Currency;
import javafx.collections.FXCollections;
import javafx.scene.control.TableView;
import java.util.List;
import com.saburi.finance.dbaccess.SaleOrderDetailDA;
import com.saburi.finance.entities.SaleOrder;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TablePosition;
import javafx.collections.ObservableList;
import com.saburi.finance.entities.Item;
import java.io.IOException;
import java.util.stream.Collectors;
import javafx.application.Platform;
import com.saburi.finance.utils.FinanceEnums.InvoiceStatus;



public class SaleOrderController extends EditController {

    private final SaleOrderDA oSaleOrderDA = new SaleOrderDA();
    @FXML
    private TextField txtSaleOrderID;
    @FXML
    private DatePicker dtpOrderDate;
    @FXML
    private TextArea txaShipAddress;
    @FXML
    private ComboBox cboSellTo;
    @FXML
    private MenuItem cmiSelectSellTo;
    @FXML
    private ComboBox cboBillTo;
    @FXML
    private MenuItem cmiSelectBillTo;
    @FXML
    private ComboBox cboCurrency;
    @FXML
    private MenuItem cmiSelectCurrency;

    @FXML
    private TextField txtAmount;
    @FXML
    private TextArea txaAmountWords;
    @FXML
    private TableView<SaleOrderDetailDA> tblSaleOrderDetails;
    @FXML
    private MenuItem cmiSelectItem;
    private final CustomerDA oCustomerDA = new CustomerDA();
    private final CurrencyDA oCurrencyDA = new CurrencyDA();
    ItemDA oItemDA = new ItemDA();
    @FXML
    private TableColumn<SaleOrderDetailDA, String> tbcSaleOrderDetailItemID;
    @FXML
    private TableColumn<SaleOrderDetailDA, Integer> tbcSaleOrderDetailBaseQuantity;
    @FXML
    private TableColumn<SaleOrderDetailDA, String> tbcSaleOrderDetailUnitMeasure;

    @FXML
    private TableColumn<SaleOrderDetailDA, String> tbcSaleOrderDetailUnitPrice;
    @FXML
    private TableColumn<SaleOrderDetailDA, String> tbcSaleOrderDetailDiscount;
    @FXML
    private Customer selectedBillToDA;

    @Override
    public void initialize(URL url, ResourceBundle rb) {
        try {
            loadDBEntities(oCustomerDA.getCustomers(), cboSellTo);
            loadDBEntities(oCustomerDA.getCustomers(), cboBillTo);
            loadDBEntities(oCurrencyDA.getCurrencys(), cboCurrency);

            tblSaleOrderDetails.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY);
            setTableEditable(tblSaleOrderDetails);
            addRow(tblSaleOrderDetails, new SaleOrderDetailDA());
            cmiSelectItem.setOnAction(e -> loadItem());
            this.primaryKeyControl = txtSaleOrderID;
            this.dbAccess = oSaleOrderDA;
            this.restrainColumnConstraint = false;
            this.minSize = 1000;
            this.setNextSaleOrderID();
            setSaleOrderDetailItem();
            setSaleOrderDetailBaseQuantity();
            setSaleOrderDetailUnitPrice();
            setSaleOrderDetailDiscount();
            selectItem(FinanceNavigate.MAIN_CLASS, cmiSelectSellTo, oCustomerDA, "Customer", "Customer", 700, 400, cboSellTo, true);
            selectItem(FinanceNavigate.MAIN_CLASS, cmiSelectBillTo, oCustomerDA, "Customer", "Customer", 700, 400, cboBillTo, true);
            selectItem(FinanceNavigate.MAIN_CLASS, cmiSelectCurrency, oCurrencyDA, "Currency", "Currency", 700, 400, cboCurrency, true);
            dtpOrderDate.setValue(LocalDate.now());
            cboBillTo.setOnAction(e -> {
                this.selectedBillToDA = ((Customer) getEntity(cboBillTo));
                tblSaleOrderDetails.getItems().forEach(bi -> {
                    if (bi.getItemDA().getItemID() != null) {
                        setPrices(bi);
                        calculateAmount();
                        tblSaleOrderDetails.refresh();
                    }
                });

            });

            tblSaleOrderDetails.setOnMouseClicked(e -> {
                final TablePosition<SaleOrderDetailDA, String> focusedCell = tblSaleOrderDetails
                        .focusModelProperty().get().focusedCellProperty().get();
                if (focusedCell.getTableColumn() == tbcSaleOrderDetailUnitMeasure) {
                    loadUnitMeasure();
                }

            });
        } catch (Exception e) {
            errorMessage(e);
        } finally {
        }
    }

    @Override
    protected void save() {
        try {
            this.editSuccessful = false;
            String saleOrderID = getText(txtSaleOrderID, "Sale Order ID");
            LocalDate orderDate = getDate(dtpOrderDate, "Order Date");
            String shipAddress = getText(txaShipAddress, "Ship Address");
            Customer sellTo = (Customer) getEntity(cboSellTo, "Sell To");
            Customer billTo = (Customer) getEntity(cboBillTo, "Bill To");
            Currency currency = (Currency) getEntity(cboCurrency, "Currency");
            EntryModes entryMode = EntryModes.Manual;
            double amount = getDouble(txtAmount, "Amount");
            String amountWords = getText(txaAmountWords, "Amount Words");
            List<SaleOrderDetailDA> saleOrderDetailsDAs = tblSaleOrderDetails.getItems();
            saleOrderDetailsDAs.removeIf((p) -> p.getItem() == null);

            SaleOrderDA saleOrderDA = new SaleOrderDA(saleOrderID, orderDate, shipAddress, sellTo, billTo, currency, entryMode, amount, amountWords);
            saleOrderDetailsDAs.forEach(e -> {
                e.setSaleOrder((SaleOrder) saleOrderDA.getSaleOrder());
                e.setInvoiceStatus(InvoiceStatus.Pending);
            });
            saleOrderDA.setSaleOrderDetailsDAs(saleOrderDetailsDAs);
            String buttonText = btnSave.getText();
            if (buttonText.equalsIgnoreCase(FormMode.Save.name())) {
                saleOrderDA.save();
                message("Saved Successfully");
                clear();
            } else if (buttonText.equalsIgnoreCase(FormMode.Update.name())) {
                saleOrderDA.update();
                message("Updated Successfully");
            }
            this.dbAccess = saleOrderDA;
            this.editSuccessful = true;
        } catch (Exception e) {
            errorMessage(e);
        } finally {
        }
    }

    @Override
    protected void delete() {
        try {
            String saleOrderID = getText(txtSaleOrderID, "Sale Order ID");
            SaleOrderDA saleOrderDA = oSaleOrderDA.get(saleOrderID);
            if (!warningOk("Confirm Delete", "You are about to delete a record with ID: " + saleOrderID + " Are you sure you want to continue?", "Remember this action cannot be un done")) {
                return;
            }
            if (saleOrderDA.delete()) {
                message("Deleted Successfully");
                this.clear();
            }
        } catch (Exception e) {
            errorMessage(e);
        }
    }

    @Override
    public void loadData() {
        try {
            String saleOrderID = getText(txtSaleOrderID, "Sale Order ID");

            SaleOrderDA saleOrderDA = oSaleOrderDA.get(saleOrderID);
            txtSaleOrderID.setText(saleOrderDA.getSaleOrderID());
            dtpOrderDate.setValue((LocalDate) saleOrderDA.getOrderDate());
            txaShipAddress.setText(saleOrderDA.getShipAddress());
            cboSellTo.setValue(saleOrderDA.getSellTo());
            cboBillTo.setValue(saleOrderDA.getBillTo());
            cboCurrency.setValue(saleOrderDA.getCurrency());
            txtAmount.setText(formatNumber(saleOrderDA.getAmount()));
            txaAmountWords.setText(saleOrderDA.getAmountWords());
            tblSaleOrderDetails.setItems(FXCollections.observableArrayList(saleOrderDA.getSaleOrderDetailsDAs()));
            addRow(tblSaleOrderDetails, new SaleOrderDetailDA());

        } catch (Exception e) {
            errorMessage(e);
        }

    }

    private void setNextSaleOrderID() {
        try {
            if (btnSave.getText().equalsIgnoreCase(FormMode.Save.name())) {
                txtSaleOrderID.setText(oSaleOrderDA.getNextSaleOrderID(oSaleOrderDA.getNextIdHelper()));
            }
        } catch (Exception e) {
            errorMessage(e);
        }
    }

    private void setSaleOrderDetailItem() {
        tbcSaleOrderDetailItemID.setCellFactory(EditCell.StringTableColumn());
        tbcSaleOrderDetailItemID.setOnEditCommit(event -> {
            final String value = event.getNewValue() != null ? event.getNewValue()
                    : event.getOldValue();
            Item item = oItemDA.getItem(value);
            if (item == null) {
                Platform.runLater(() -> message("No Item with Id " + value + " found"));
                return;
            }
            SaleOrderDetailDA saleOrderDetailDA = event.getTableView().getItems()
                    .get(event.getTablePosition().getRow());
            saleOrderDetailDA.setItem(item);
            setPrices(saleOrderDetailDA);
            tblSaleOrderDetails.refresh();
            addRow(tblSaleOrderDetails, new SaleOrderDetailDA());
        });
    }

    private void setSaleOrderDetailBaseQuantity() {
        tbcSaleOrderDetailBaseQuantity.setCellFactory(EditCell.IntegerTableColumn());
        tbcSaleOrderDetailBaseQuantity.setOnEditCommit(event -> {
            final int value = event.getNewValue() != null ? event.getNewValue()
                    : event.getOldValue();
            ((SaleOrderDetailDA) event.getTableView().getItems()
                    .get(event.getTablePosition().getRow()))
                    .setBaseQuantity(value);
            tblSaleOrderDetails.refresh();
            addRow(tblSaleOrderDetails, new SaleOrderDetailDA());
            this.calculateAmount();
        });
    }

    private void setSaleOrderDetailUnitPrice() {
        tbcSaleOrderDetailUnitPrice.setCellFactory(EditCell.StringTableColumn());
        tbcSaleOrderDetailUnitPrice.setOnEditCommit(event -> {
            final String value = event.getNewValue() != null ? event.getNewValue()
                    : event.getOldValue();
            ((SaleOrderDetailDA) event.getTableView().getItems()
                    .get(event.getTablePosition().getRow()))
                    .setUnitPrice(defortNumberOptional(value));
            tblSaleOrderDetails.refresh();
            addRow(tblSaleOrderDetails, new SaleOrderDetailDA());
        });
        this.calculateAmount();
    }

    private void setSaleOrderDetailDiscount() {
        tbcSaleOrderDetailDiscount.setCellFactory(EditCell.StringTableColumn());
        tbcSaleOrderDetailDiscount.setOnEditCommit(event -> {
            final String value = event.getNewValue() != null ? event.getNewValue()
                    : event.getOldValue();
            ((SaleOrderDetailDA) event.getTableView().getItems()
                    .get(event.getTablePosition().getRow()))
                    .setDiscount(defortNumberOptional(value));
            tblSaleOrderDetails.refresh();
            addRow(tblSaleOrderDetails, new SaleOrderDetailDA());
        });
        this.calculateAmount();
    }

    @Override
    protected void clear() {
        txtSaleOrderID.clear();
        dtpOrderDate.setValue(null);
        txaShipAddress.clear();
        cboSellTo.setValue(null);
        cboBillTo.setValue(null);
        cboCurrency.setValue(null);
        txtAmount.clear();
        txaAmountWords.clear();
        tblSaleOrderDetails.getItems().clear();
        addRow(tblSaleOrderDetails, new SaleOrderDetailDA());
        this.setNextSaleOrderID();

    }

    private void loadItem() {
        try {
            ObservableList<SaleOrderDetailDA> selectedItems = tblSaleOrderDetails.getSelectionModel().getSelectedItems();
            if (selectedItems.isEmpty() || selectedItems.size() > 1) {
                return;
            }
            ItemDA itemDA = (ItemDA) getSelectedItem(FinanceNavigate.MAIN_CLASS, new ItemDA(), "Item", "Items", 400, 450, tblSaleOrderDetails, false);

            if (itemDA == null) {
                return;
            }

            if (tblSaleOrderDetails.getItems().stream().map(SaleOrderDetailDA::getItemDA).collect(Collectors.toList()).contains(itemDA)) {
                throw new Exception("The record with id: " + itemDA.getId() + " is already selected");
            }

            final TablePosition<SaleOrderDetailDA, String> focusedCell = tblSaleOrderDetails
                    .focusModelProperty().get().focusedCellProperty().get();
            SaleOrderDetailDA saleOrderDetailDA = tblSaleOrderDetails.getItems().get(focusedCell.getRow());
            saleOrderDetailDA.setItem(itemDA.getItem());
            setPrices(saleOrderDetailDA);
            tblSaleOrderDetails.refresh();
            calculateAmount();
            addRow(tblSaleOrderDetails, new SaleOrderDetailDA());

        } catch (IOException e) {
            errorMessage(e);
        } catch (Exception e) {
            errorMessage(e);
        }
    }

    private void setPrices(SaleOrderDetailDA saleOrderDetailDA) {
        saleOrderDetailDA.setUnitPrice(saleOrderDetailDA.getItemDA().getUnitPrice(selectedBillToDA));
        saleOrderDetailDA.setDiscount(saleOrderDetailDA.getItemDA().getDiscount(selectedBillToDA));
    }

    public void calculateAmount() {
        double totalAmount = tblSaleOrderDetails.getItems().stream().mapToDouble(SaleOrderDetailDA::getAmount).sum();
        txtAmount.setText(formatNumber(totalAmount));
        txaAmountWords.setText(NumberToWord.toWords(totalAmount));

    }

    private void loadUnitMeasure() {
        try {
            ObservableList<SaleOrderDetailDA> selectedItems = tblSaleOrderDetails.getSelectionModel().getSelectedItems();
            if (selectedItems.isEmpty() || selectedItems.size() > 1) {
                return;
            }

            final TablePosition<SaleOrderDetailDA, String> focusedCell = tblSaleOrderDetails
                    .focusModelProperty().get().focusedCellProperty().get();

            if (focusedCell == null) {
                return;
            }

            SaleOrderDetailDA saleOrderDetailDA = tblSaleOrderDetails.getItems().get(focusedCell.getRow());

            ItemDA itemDA = saleOrderDetailDA.getItemDA();
            if (itemDA == null) {
                return;
            }
            List<MeasureRelationDA> measureRelationDAs = new MeasureGroupDA().get(itemDA.getMeasureGroup().getMeasureGroupID()).getAllMeasureRelationsDAs();

            MeasureRelationDA measureRelationDA = (MeasureRelationDA) getSelectedItem(FinanceNavigate.MAIN_CLASS, new MeasureRelationDA(), measureRelationDAs, "View", "Item", 400, 450, tblSaleOrderDetails, false);

            if (measureRelationDA != null) {
                saleOrderDetailDA.setUnitMeasure(measureRelationDA.getDisplayKey());
                saleOrderDetailDA.setMeasureSize(measureRelationDA.getBaseSize());

            }

            tblSaleOrderDetails.refresh();
            calculateAmount();

        } catch (IOException e) {
            errorMessage(e);
        } catch (Exception e) {
            errorMessage(e);
        }
    }

}
